{% set name = "gettsim" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gettsim-{{ version }}.tar.gz
  sha256: ad65c26deeb554e6f7b3428e60e91c91ad0df3e0eb14d432b8757b035ce93267

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.0
    - pip
  run:
    - python >={{ python_min }}
    - astor
    - dags
    - networkx
    - numpy
    - numpy_groupies
    - pandas
    - plotly
    - pygments
    - pygraphviz
    - pytest
    - pyyaml

test:
  imports:
    - gettsim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iza-institute-of-labor-economics/gettsim
  summary: The German Taxes and Transfers SIMulator
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmgaudecker
